services:
  postgres:
    image: postgres:16
    container_name: recipes-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
    volumes:
      - recipes-data:/var/lib/postgresql/data

volumes:
  recipes-data:

